### PR TITLE
Changed autocapitalize default to none

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
`autocapitalize="off"` was deprecated as of iOS 5.0. Firefox 83 updated to reflect this as well, and was causing our unit tests to fail. This updates the autocomplete component to use `none` instead of `off`.

https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/Attributes.html#//apple_ref/doc/uid/TP40008058-autocapitalize

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-lookup?_sp.spa=pr-autocomplete-autocapitalize-fix](https://developer.blackbaud.com/skyux-lookup?_sp.spa=pr-autocomplete-autocapitalize-fix)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-lookup?_sp.spa=pr-autocomplete-autocapitalize-fix](https://developer.blackbaud.com/skyux-lookup?_sp.spa=pr-autocomplete-autocapitalize-fix)

**Review by Blackbaud-SteveBrush — COMMENTED** [review]
Just curious, why did the `autocapitalize` change require you to delete screenshots?

**Comment by Blackbaud-AlexKingman** [comment]
> Just curious, why did the `autocapitalize` change require you to delete screenshots?

Sorry, forgot to mention - it didn't. The screenshots had some buttons in them and the spacing/padding to buttons was changed upstream. That caused the screenshots to be slightly different. It had nothing to do with this particular PR.

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
